# Generated by Django 5.0.4 on 2024-04-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_transfer_date_alter_transferitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='mode',
            field=models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10),
        ),
    ]
