# Generated by Django 5.0.4 on 2024-04-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_transfer_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='transfer',
            name='mode',
            field=models.CharField(choices=[('entry', 'ورود'), ('exit', 'خروج')], max_length=10),
        ),
    ]
